
name: Tag and publish a new version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  tah-and-publish:
    runs-on: ubuntu-latest
    if:  '${{ inputs.version }}'
    steps:
      - name: Foo
        run: echo 1

